spring.application.name=train-gateway
server.port=8000

# 路由配置
spring.cloud.gateway.routes[0].id=member
spring.cloud.gateway.routes[0].uri=http://localhost:8001
spring.cloud.gateway.routes[0].predicates[0]=Path=/member/**

spring.cloud.gateway.routes[1].id=business
spring.cloud.gateway.routes[1].uri=http://localhost:8002
spring.cloud.gateway.routes[1].predicates[0]=Path=/business/**

spring.cloud.gateway.routes[2].id=batch
spring.cloud.gateway.routes[2].uri=http://localhost:8004
spring.cloud.gateway.routes[2].predicates[0]=Path=/batch/**

#允许请求来源
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=*

#允许请求头
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*

#允许请求方法
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*

#是否允许带cookie
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

#跨域检测有效期
spring.cloud.gateway.globalcors.cors-configurations.[/**].max-age=3600

# JWT 相关配置
# 密钥（建议至少 32 位以上字符串，保证安全）
jwt.secret=haijian
# 过期时间（单位：秒，这里设置为 24 小时）
jwt.expire=3600000