###
GET http://localhost:8000/member/test
Accept: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3NzAzMDI5NTksIm1vYmlsZSI6IjEzMDAwMDAwMDAwIiwiaWQiOjIwMTg4NzYwMTI5MDQ4NDEyMTYsImV4cCI6MTc3MzkwMjk1OSwiaWF0IjoxNzcwMzAyOTU5fQ.49UXDrgk-vH8jRZyziniWZc82iTayH-qSaZeFd3IiNQ
